### ISSUE TITLE
startup message to stderr

### ISSUE THREAD

**Issue by randomee** [gdemin/excel.link#10]
It'd be nice to be able to turn off the library load message "To Daniela Khazova who constantly inspires me..."  
Or for it to at least respect the "quietly" option:
library(excel.link, quietly=TRUE)

I have a set of monitoring scripts that look at the exit status, and stderr, and this is messing them up.

(yes, I can use suppressMessages(), but that seems a bit extreme)

I appreciate all of the work you've put in. and work on my previous requests!

Thanks!

**Comment by gdemin** [comment]
Package doesn't know about value of `quietly` argument. Conventional method for suppressing package startup messages is `suppressPackageStartupMessages`, so you can use `suppressPackageStartupMessages(library(excel.link))`. Or, for multiple packages:
```
suppressPackageStartupMessages({
    library(excel.link)
    library(data.table)
    library(ggplot2)
    })
```
