### ISSUE TITLE
Reading a file with multiple passwords into R

### ISSUE THREAD

**Issue by pbiondi** [gdemin/excel.link#11]
Is there a way to set multiple password arguments for xl.read.file?

**Comment by gdemin** [comment]
Could you describe use case for multiple passwords for single Excel file? As far as I know single Excel file has single password.

**Comment by pbiondi** [comment]
Hi Gregory,

The file is locked by two different departments for my project. It is the same password for both locks. 

The first is for access to the file, and the second decided whether or not I will have the ability to edit the file vs. read-only

**Comment by pbiondi** [comment]
It works, thank you SO much!

Cheers,
Peter

**Comment by gdemin** [comment]
Fixed in version 0.9.8
