### ISSUE TITLE
Package not Available on 3.5.2

### ISSUE THREAD

**Issue by S-UP** [gdemin/excel.link#16]
Hi,

Wanted to try out your package but get warning:
`package ‘excel.link’ is not available (for R version 3.5.2)`

Do you need to update the package or can I somehow work around this?

**Comment by gdemin** [comment]
Hi,
Which operating system do you use?

**Comment by S-UP** [comment]
I am on Ubuntu 18.

**Comment by gdemin** [comment]
Yes, it is Windows only. It use COM to exchange data with running Excel instance.
