### ISSUE TITLE
package ‘excel.link’ is not available (for R version 3.6.1)

### ISSUE THREAD

**Issue by echorohit** [gdemin/excel.link#18]
Warning message:
package ‘excel.link’ is not available (for R version 3.6.1)

Os: MacOS Mohave

**Comment by gdemin** [comment]
`excel.link` is only for Windows due to COM technology. Sorry for inconveniences.

**Comment by r0bis** [comment]
> `excel.link` is only for Windows due to COM technology. Sorry for inconveniences.

Thanks for your work on this. The issue of Windows only  should really be more visible on the main README.md file. on your repo front page. I was looking for package that would work on linux and your commit messages are the only place that mention an operating system. `Commit from Linux - lineendings are changed` Would you please update this?
Kind regards,

**Comment by gdemin** [comment]
@r0bis 
There is a sentence `Microsoft Excel is required for this package.` in the package description on CRAN. I will also add a warning to the readme for GitHub users.
As for mention Linux - CRAN team requires that package pass CRAN check on Linux. I don't know why they want it but I made it.

**Comment by r0bis** [comment]
Thanks, I did not notice that sentence, sorry. But I think that Github Readme is a significantly more visible piece of description; maybe I am wrong, but for me it is; so it would not hurt to put a warning there too.
