### ISSUE TITLE
 R 4.0.1 aborts when xl.get.excel() is executed

### ISSUE THREAD

**Issue by larsot23** [gdemin/excel.link#24]
When running the following two lines of code R 4.0.1 aborts.  For various versions R 3 there is no problem. I have included run information below:

library(excel.link)
xls <- xl.get.excel()
####################

R version 4.0.1 Patched (2020-06-06 r78651) -- "See Things Now"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(excel.link)

To Daniela Khazova who constantly inspires me...
> 
> version
               _                                          
platform       x86_64-w64-mingw32                         
arch           x86_64                                     
os             mingw32                                    
system         x86_64, mingw32                            
status         Patched                                    
major          4                                          
minor          0.1                                        
year           2020                                       
month          06                                         
day            06                                         
svn rev        78651                                      
language       R                                          
version.string R version 4.0.1 Patched (2020-06-06 r78651)
nickname       See Things Now                             
> sessionInfo()
R version 4.0.1 Patched (2020-06-06 r78651)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=Danish_Denmark.1252  LC_CTYPE=Danish_Denmark.1252   
[3] LC_MONETARY=Danish_Denmark.1252 LC_NUMERIC=C                   
[5] LC_TIME=Danish_Denmark.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] excel.link_0.9.8-1

loaded via a namespace (and not attached):
[1] compiler_4.0.1 tools_4.0.1   
> osVersion
[1] "Windows 10 x64 (build 18363)"
> xls <- xl.get.excel()
####

This is where R is completed aborted and shot down.

I have been using excel.link for several years under R3 without any problems, and I would like to continue to use excel.link.

Regards,
Lars

**Comment by gdemin** [comment]
Thank you for reporting.
I know about this issue. It arises in RDCOMClient package on which 'excel.link' depends. New version will be released just after the fixing RDCOMCLient issue: https://github.com/omegahat/RDCOMClient/issues/19

**Comment by rsh52** [comment]
Any idea on when this might be updated to accommodate R4.0+? I realize it's dependent on RDCOMClient.

Thank you,
--Rich

**Comment by gdemin** [comment]
Sorry, I don't know how to fix it. So only vague answer "just after the fixing RDCOMClient".

**Comment by tamamushiiro** [comment]
> Sorry, I don't know how to fix it. So only vague answer "just after the fixing RDCOMClient".

Could using [this fork of RDCOMClient](https://github.com/BSchamberger/RDCOMClient) help in solving this issue?

**Comment by gdemin** [comment]
@tamamushiiro 
Thanks, I will look at it next week.

**Comment by florian-sk** [comment]
Any light shed in that matter already?

I incorporated the functionalities around communicating with the active excel instance heavily into my (and my colleagues) workflows. We can't go on using R3.* forever :-)

I was able to install the RDCOMclient package using the repo pointed out in Tamamushiiro's post with the latest R version:
install.packages("RDCOMClient", repos = "http://www.omegahat.net/R")

**Comment by gdemin** [comment]
@florian-sk 
Yes, I see that RDCOMClient is working. So I will try to release new version this week.

**Comment by florian-sk** [comment]
Uh, exciting. Thanks for the efforts!!

**Comment by gdemin** [comment]
New excel.link version  is on CRAN now and will be build in the several days. It works on my machine and I hope will solve this long-standing issue.

**Comment by gdemin** [comment]
It seems new CRAN version still failed when installed. I continue investigation:(

**Comment by gdemin** [comment]
@gabgel From which version of R did you upgrade? Could you try to reinstall excel.link from CRAN?

**Comment by gdemin** [comment]
It seems bug was fixed with version 0.9.10 at 2021-11-02

**Comment by florian-sk** [comment]
Awesome job! 
Can confirm it works fine with R 4.0.4 and excel-link 0.9.10.
