### ISSUE TITLE
No 'R_connection_examples.xlsm' with examples in the package 'doc' folder.

### ISSUE THREAD

**Issue by mikmar16** [gdemin/excel.link#26]
Have done the install and there is no example xlsm in the doc folder. Also cant find it on the gdemin/excel.link in GitHub

**Comment by gdemin** [comment]
Thank you. It seems I made something wrong when prepare the last release. I will fix it in the next release. 
This file is present in the previous commits - https://github.com/gdemin/excel.link/blob/4204a028fdeade7e5645a33f72e7d095863cd334/inst/doc/R_connection_examples.xlsm

**Comment by mikmar16** [comment]
Thanks! Thought I was going mad! This looks great by the way. Thanks for
making.

**Comment by gdemin** [comment]
Fixed in 0.9.10. No examples are in the 'xlsx' folder under package folder
