### ISSUE TITLE
ERROR:  Windows-only package

### ISSUE THREAD

**Issue by FortuneHadebe90** [gdemin/excel.link#28]
I'm using R version 4.0.5 on Rstudio connect and get the following install error:
Code:
install.packages("~/PIC Database/packages/excel.link_0.9.11.tar.gz", repos = NULL, type = "source")

Error:
Installing package into ‘/home/p536644/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
ERROR:  Windows-only package
* removing ‘/home/p536644/R/x86_64-pc-linux-gnu-library/4.0/excel.link’
Warning in install.packages :
  installation of package ‘/home/p536644/PIC Database/packages/excel.link_0.9.11.tar.gz’ had non-zero exit status

I am running windows - not sure what's causing this.

**Comment by gdemin** [comment]
In your error description all paths are Linux paths. I am not familiar with RStudio Connect but can it use Linux VM or WSL inside?

**Comment by FortuneHadebe90** [comment]
Apologies. It's not connect but Rstudio server. It seems it is a Linux VM, now that you mention it. And I understand excel.link only works on windows from what I've seen. Is there a Linux-friendly alternative for dealing formulae-based excel files - apart from XLConnect ? 

I trying to load a file saved with formulae into r but it loads as zeros instead of values.

**Comment by gdemin** [comment]
Perhaps, openxlsx does the trick: https://cran.r-project.org/package=openxlsx
