### ISSUE TITLE
Execute an R script from Excel

### ISSUE THREAD

**Issue by FelipeCarrillo** [gdemin/excel.link#34]
I am trying to execute an R script using Rscript in VBA Excel book. However, excel.link opens a new instance of excel when the R script is executed and ignores my workbook. How can I point out to my workbook? xl.workbook.activate("my_book") doesn't seem to work. Here is what my R script looks like;

```
library(excel.link)
 setwd("C:/Yuba_Project")
getwd()
FinalData <- head(iris)
 FinalData
 #xl.workbook.open("Excel_link.xlsm")
 xl.workbook.activate("Excel_link.xlsm")
#xl.sheet.activate("summary")
xlc[a2:h2] = NA
  xlc[a1] = FinalData
```
And I am trying to execute the above R script from Excel VBA like below:

```
Sub test()
Dim myPath As String
'ChDir ThisWorkbook.path
myPath = "RScript " & "C:\Users\my_file\Desktop\R_code_5-20-22\Rtest.r"
Call shell(myPath, vbHide)
```
Question: Does the book has to be close in order to execute the R script?

**Comment by gdemin** [comment]
It seems a new instance of Excel is activated. To call R from Excel it is better to use functions from the workbook in the package. You can find it in the 'library\excel.link\xlsx\R_connection_examples.xlsm' or here:  https://github.com/gdemin/excel.link/blob/master/inst/xlsx/R_connection_examples.xlsm Particulary, you can be interested in `ExecInR` VBA function.

**Comment by FelipeCarrillo** [comment]
Thanks for the clarification. A follow up question if you dont mind. Can I use ExecInR this way: ExecInR("plot(rnorm(100))")
Felipe D. CarrilloFish and Wildlife BiologistDepartment of the InteriorU.S. Fish and Wildlife, San FranciscoBay Delta OfficeCalifornia, USAhttps://www.fws.gov/office/san-francisco-bay-delta-fish-and-wildlife
 

    On Wednesday, September 11, 2024 at 03:23:09 AM PDT, Gregory Demin ***@***.***> wrote:  
 
 


It seems a new instance of Excel is activated. To call R from Excel it is better to use functions from the workbook in the package. You can find it in the 'library\excel.link\xlsx\R_connection_examples.xlsm' or here: https://github.com/gdemin/excel.link/blob/master/inst/xlsx/R_connection_examples.xlsm Particulary, you can be interested in ExecInR VBA function.

**Comment by gdemin** [comment]
You need to define graphic device. For example, `ExecInR ("png('c:/temp/1.png');plot(rnorm(100));dev.off()")` will save plot to c:/temp/1.png

**Comment by FelipeCarrillo** [comment]
This is great!!! I will try to practice to get more familiar with the functions. Where can I read more about the functions you use in the workbook? I want to learn more about  ExecInR, ExecRangeInR etc. 
Also, I want to let you know just in case you are not aware of it. I noticed that the 'Environ' vba function in the workbook does not work. It returns empty when the code is looking for 'R_HOME'. 
In the R console, if I type: Sys.getenv("R_HOME"), I get the R_HOME directory, However, with Environ in vba returns empty.
Thank you for the workbook. 
Felipe D. CarrilloFish and Wildlife BiologistDepartment of the InteriorU.S. Fish and Wildlife, San FranciscoBay Delta OfficeCalifornia, USAhttps://www.fws.gov/office/san-francisco-bay-delta-fish-and-wildlife
 

    On Thursday, September 12, 2024 at 07:05:29 AM PDT, Gregory Demin ***@***.***> wrote:  
 
 


You need to define graphic device. For example, ExecInR ("png('c:/temp/1.png');plot(rnorm(100));dev.off()") will save plot to c:/temp/1.png

**Comment by gdemin** [comment]
> Where can I read more about the functions you use in the workbook?

There are comments in VBA code in the workbook and small vignette: https://cran.r-project.org/web/packages/excel.link/vignettes/CallingRFromExcel.html

**Comment by FelipeCarrillo** [comment]
Thanks. Got the vignette. Gregory, a twofold question and I won't bother you again. I just need clarification on these two below:
1.- Does the function ExecRangeInR takes only a pre- created named range such as ExecRangeInR [named_range] or also takes a hard-coded range
     such as ExecRangeInR(range(MySheet!A1:A10) or ExecRangeInR( Range(Selection, Selection.End(xlDown)).Select?
2.- Can I use a long R script with ExecInR? If so, the script must be in one really long line separated by semicolon(;) or the script can be breakdown into multiple lines of code? Can you give me a short example on how I can break an R script into 2 or 3 lines using ExecInR ?
Thanks a lot

    On Friday, September 13, 2024 at 02:54:45 PM PDT, Gregory Demin ***@***.***> wrote:  
 
 



Where can I read more about the functions you use in the workbook?


There are comments in VBA code in the workbook and small vignette: https://cran.r-project.org/web/packages/excel.link/vignettes/CallingRFromExcel.html

**Comment by gdemin** [comment]
1. Yes, ExecRangeInR should work  with dynamic ranges.
2. You can use multiline script. Just copy your script from text editor and paste into single cell. And then use this cell value in the ExecInR as argument.

**Comment by FelipeCarrillo** [comment]
Thanks for the help. I meant a multiline script executed from vba module only. Something like ExecInR(multiple lines of r code)

Yahoo Mail: Search, Organize, Conquer 
 
  On Tue, Sep 17, 2024 at 2:42 PM, Gregory ***@***.***> wrote:   

   
   - Yes, ExecRangeInR should work with dynamic ranges.
   - You can use multiline script. Just copy your script from text editor and paste into single cell. And then use this cell value in the ExecInR as argument.

**Comment by gdemin** [comment]
As far as I know you can connect lines as `"line1" & vbNewLine & "line2"`. But it's better to ask in a  specialized VBA community.

**Comment by FelipeCarrillo** [comment]
Gregory, I promise this is my last question for a while. I am just having a hard time concatenating two lines of code into the same "ExecInR" function call. For example,
This works because is a one liner:ExecInR ("png(""1.png"");plot(rnorm(500),col=""blue"");p1 = current.graphics(filename = ""1.png"");dev.off();xlrc [""'Rgraphic'!O19""] = p1")
But if I try to break it into two lines I get an error message even though I am continuing my "ExecInR" call.For example, the below won't work:
ExecInR ("png(""1.png"");plot(rnorm(500),col=""blue"");  & vbNewLine &"p1 = current.graphics(filename = ""1.png"");dev.off();xlrc [""'Rgraphic'!O19""] = p1")"



Felipe D. CarrilloFish and Wildlife BiologistDepartment of the InteriorU.S. Fish and Wildlife, San FranciscoBay Delta OfficeCalifornia, USAhttps://www.fws.gov/office/san-francisco-bay-delta-fish-and-wildlife
 

    On Wednesday, September 18, 2024 at 02:55:20 AM PDT, Gregory Demin ***@***.***> wrote:  
 
 


As far as I know you can connect lines as "line1" & vbNewLine & "line2". But it's better to ask in a specialized VBA community.

**Comment by gdemin** [comment]
It seems, you need more quotes:
```vb
ExecInR ("png(""1.png"");plot(rnorm(500),col=""blue"");"  & vbNewLine &"p1 = current.graphics(filename = ""1.png"");dev.off();xlrc [""'Rgraphic'!O19""] = p1")
```
