### ISSUE TITLE
Opening new workbook only if not already open

### ISSUE THREAD

**Issue by randomee** [gdemin/excel.link#6]
Right now, if I open a workbook, then try to open it again, R hangs while excel asks if I want to re-open & discard changes.

It'd be really nice if there were a wrapper to open a file if and only if it's not open yet.  A singleton pattern of sorts.  

I know I can wrap xl.workbook.open to call/check xl.workbooks 1st, but it seems it would be common issue.

Thanks!

**Comment by gdemin** [comment]
Ok, I will fix it in the next version/

**Comment by randomee** [comment]
great.  Thanks!

**Comment by gdemin** [comment]
Fixed in version 0.9.7
